import type { Metadata } from "next";

import "./globals.css";

import QueryProvider from "@/provider/QueryProvider";
import { LoadingView } from "@/shared/ui/loadingView";
import { SessionProvider } from "@/provider/SessionProvider";
import { LayoutWrapper } from "@/widgets/LayoutWrapper";

export const metadata: Metadata = {
  title: "개발중",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko" >
      <body cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
